<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
    <DefaultItemExcludes>$(DefaultItemExcludes);third_party/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="third_party/OVRSharp/OVRSharp/OVRSharp.csproj" />
    <EmbeddedResource Include="third_party/OVRSharp/LICENSE" LogicalName="ThirdParty.OVRSharp.LICENSE" />
  </ItemGroup>
</Project>
